export const PBT_LIST = [
  { type: 'MD', name: 'Sabak Bernam', scene: 'puteri', logo: 'mdsb.png' },
  { type: 'MP', name: 'Ampang Jaya', scene: 'ampang', logo: 'mpaj.png' },
  { type: 'MD', name: 'Kampar', scene: 'kulai', logo: 'mdkampar.png' },
  { type: 'MD', name: 'Tapah', scene: 'pontian', logo: 'mdtapah.png' },
  { type: 'MD', name: 'Tg. Malim', scene: 'other', logo: 'mdtm.png' },
  { type: 'MP', name: 'Pontian', scene: 'pontian', logo: 'mppn.png' },
  { type: 'MP', name: 'Port Dickson', scene: 'puteri', logo: 'mppd.png' },
  { type: 'MP', name: 'Kulai', scene: 'kulai', logo: 'mpku.png' },
  { type: 'MP', name: 'Teluk Intan', scene: 'ampang', logo: 'mpti.png' },
  { type: 'MD', name: 'Peng. Hulu', scene: 'other', logo: 'mdph.png' },
  { type: 'MD', name: 'Gerik', scene: 'kulai', logo: 'mdgerik.png' },
  { type: 'MD', name: 'Lenggong', scene: 'pontian', logo: 'mdlg.png' },
  { type: 'MD', name: 'Batu Gajah', scene: 'puteri', logo: 'mdbg.png' },
  { type: 'MD', name: 'Perak Tengah', scene: 'ampang', logo: 'mdpt.png' },
  { type: 'MP', name: 'Manjung', scene: 'other', logo: 'mpm.png' },
  { type: 'MP', name: 'Taiping', scene: 'pontian', logo: 'mptaiping.png' },
  { type: 'MD', name: 'Kerian', scene: 'kulai', logo: 'mdkerian.png' },
  { type: 'MD', name: 'Selama', scene: 'puteri', logo: 'mdselama.png' },
].map((pbt) => ({
  ...pbt,
  logo: `/logos/pbt/${pbt.logo}`,
  background: `/images/pbt-backgrounds/${pbt.logo.replace(/\.png$/, '.jpg')}`,
}))